"""Deleting 'subscription' model and adding 'is_active' column

Revision ID: 9f6ce732c150
Revises: 0896df0bd601
Create Date: 2026-01-21 17:52:19.583942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6ce732c150'
down_revision = '0896df0bd601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('is_active')

    op.create_table('subscription',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('member_id', sa.INTEGER(), nullable=False),
    sa.Column('plan', sa.VARCHAR(length=50), nullable=False),
    sa.Column('plan_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('subscription_date', sa.DATETIME(), nullable=False),
    sa.Column('expiry_date', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('next_plan', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], name='plans_member_id'),
    sa.ForeignKeyConstraint(['plan_name'], ['plan_details.name'], name='subscriptions_plan_name'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
